version: "2"
run:
  concurrency: 8
  go: ""
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: false
output:
  path-prefix: ""
linters:
  default: none
  enable:
    - dogsled
    - errname
    - errorlint
    - forbidigo
    - goconst
    - gomodguard
    - gosec
    - importas
    - makezero
    - misspell
    - nolintlint
    - prealloc
    - predeclared
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unused
    - whitespace
  settings:
    errorlint:
      asserts: false
    forbidigo:
      forbid:
        - pattern: ^regexp\.(Match|MatchString)$
          msg: it will re-compile the regexp for each execution; compile the regexp with regexp.Compile and store it as a singleton
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G204
        - G306
    staticcheck:
      checks:
        - all
        - -ST1003
        - -ST1022
        - -QF1003
        - -QF1004
        - -QF1012
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
          - gosec
          - makezero
        path: _test\.go
      - linters:
          - errorlint
        path: _\.gno
      - linters:
          - whitespace
        path: fixer_v2/query/internal\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  whole-files: true
  new: false
  fix: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - fixer_v2/query/internal\.go$
